name: Deploy to GitHub Pages

on:
  push:
    branches: "main"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps 

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Đoạn này sẽ tự động tìm kiếm thông minh: nếu có .output/public thì lấy, nếu có dist thì lấy, không thì lấy thư mục build gốc công khai (. là thư mục hiện tại)
          path: . 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
